### ISSUE TITLE
Any Dart-specific documentation?

### ISSUE THREAD

**Issue by hanyuone** [google/googleapis.dart#19]
I want to use the Gmail API to make an email listener in Dart, but there doesn't seem to be any documentation at all for the Dart-specific API.

Can you please provide some documentation? If there already is some, can you provide a link to where the documentation may be?

**Comment by jakobr-google** [comment]
The Dart-specific API is just client-side bindings in Dart for the APIs. For documentation on how to use them, there's the dartdoc: https://www.dartdocs.org/documentation/googleapis/0.40.0/index.html

The Gmail API dartdoc is here: https://www.dartdocs.org/documentation/googleapis/0.40.0/googleapis.gmail.v1/googleapis.gmail.v1-library.html, but it's only really useful if you already know the Gmail API (https://developers.google.com/gmail/api/).

I don't think we have any tutorials lying around, so please let us know if the above documentation isn't enough.

**Comment by Qwerp-Derp** [comment]
Yeah, the Gmail API page is really complicated - I'm trying to learn how to make an email listener, but I honestly have no idea where to start. I'm moving to Dart from Node.js, because the libraries there are killing me - none of the libraries work well with one another.

An example on the `googleapis_examples` for Gmail would be really great, if that's possible. I'll try experimenting around with the API for now, but everything's just really complex (I'm a noob to backend).
