### ISSUE TITLE
Value.nullValue is not a subtype 'String' in type cast.

### ISSUE THREAD

**Issue by hirokinko** [google/googleapis.dart#211]
I am using Datastore API.
When I got null Value from Datastore, Value.fromJson failed and returned stack traces below in my console.

```
  type 'Null' is not a subtype of type 'String' in type cast
  package:googleapis/datastore/v1.dart 3445:38  new Value.fromJson
  package:googleapis/datastore/v1.dart 1145:17  new Entity.fromJson.<fn>
  dart:collection                               MapMixin.map
  package:googleapis/datastore/v1.dart 1142:72  new Entity.fromJson
  package:googleapis/datastore/v1.dart 1191:23  new EntityResult.fromJson
  package:googleapis/datastore/v1.dart 2990:54  new QueryResultBatch.fromJson.<fn>
  dart:_internal                                ListIterable.toList
  package:googleapis/datastore/v1.dart 2992:12  new QueryResultBatch.fromJson
  package:googleapis/datastore/v1.dart 3241:32  new RunQueryResponse.fromJson
  package:googleapis/datastore/v1.dart 461:29   ProjectsResource.runQuery
```

I fixed `Value.fromJson()` in v1.dart L:3445 like below on my local environment, and It ran successfully.
https://github.com/dart-lang/googleapis/blob/master/generated/googleapis/lib/datastore/v1.dart#L3444-L3446

```diff
-     if (_json.containsKey('nullValue')) {
-       nullValue = _json['nullValue'] as core.String;
-     }
+     if (_json.containsKey('nullValue')) {
+       nullValue = _json['nullValue'] as core.Null;
+     }
```

My environment is

OS: Linux archlinux 5.11.8-zen1-1-zen 
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "linux_x64"
googleapis: 2.0.0

**Comment by vin-fandemand** [comment]
I got the same error with firestore API.
Can you please fix both of them ?
https://github.com/google/googleapis.dart/blob/07f01b7aa6985e4cafd0fd4b98724841bc9e85a1/generated/googleapis/lib/firestore/v1.dart#L4740

**Comment by kevmoo** [comment]
I just hit this as well. I think I'm going to create a model for adding overrides in another file here. Stay tuned.

**Comment by hirokinko** [comment]
@kevmoo Thanks, In my opinion, this error causes API's incorrect spec definition...
I'm hoping for a fix!
And is it better to close this issue as a duplicate?

**Comment by remidenele** [comment]
We are facing the same cast exception in our own Cloud Endpoints APIs clients generated with the [`discoveryapis_generator`](https://pub.dev/packages/discoveryapis_generator) package available on pub.dev.

In case any API response returns `null` as one of its property value, the generated `fromJson` method for that response object will throw because it tries to [explicitly cast to a non-nullable type](https://github.com/google/googleapis.dart/blob/master/discoveryapis_generator/lib/src/dart_schemas.dart#L849) when assigning the value.

Example of such generated code for a `lastAccessed` property that can be present in the response but with a `null` value:

```dart
if (_json.containsKey('lastAccessed')) {
  lastAccessed = _json['lastAccessed'] as core.String;
}
```

For now we've forked the repository and updated the generator's code so the generated code will check for the non-nullity (`!= null`) of the property's value instead of checking its presence (`containsKey()`) in the json response:

```diff
diff --git a/discoveryapis_generator/lib/src/dart_schemas.dart b/discoveryapis_generator/lib/src/dart_schemas.dart
index b8875437..0ab83961 100644
--- a/discoveryapis_generator/lib/src/dart_schemas.dart
+++ b/discoveryapis_generator/lib/src/dart_schemas.dart
@@ -842,10 +842,9 @@ class ObjectType extends ComplexDartSchemaType {
         // The super variant fromJson() will call this subclass constructor
         // and the variant descriminator is final.
         if (!isVariantDiscriminator(property)) {
-          final decodeString = property.type!
-              .jsonDecode("_json['${escapeString(property.jsonName)}']");
-          fromJsonString.writeln('    if (_json.containsKey'
-              "('${escapeString(property.jsonName)}')) {");
+          final propertyValue = "_json['${escapeString(property.jsonName)}']";
+          final decodeString = property.type!.jsonDecode(propertyValue);
+          fromJsonString.writeln('    if ($propertyValue != null) {');
           fromJsonString.writeln('      ${property.name} = $decodeString;');
           fromJsonString.writeln('    }');
         }
```

**Comment by vin-fandemand** [comment]
> @kevmoo Thanks, In my opinion, this error causes API's incorrect spec definition...
> I'm hoping for a fix!
> And is it better to close this issue as a duplicate?

Is there a different issue for the same problem? If not it is not a duplicate. As you can see, the issue is affecting many services and the fix is really simple, correct ?

**Comment by kevmoo** [comment]
It's separate fixes. We'll have to add in special-cases for each of these.

**Comment by blaueeiner** [comment]
@kevmoo What is the current state of this issue? Can a fix be expected soon?

**Comment by kevmoo** [comment]
> @kevmoo What is the current state of this issue? Can a proper fix be expected soon?

Hey @blaueeiner – it's going to be ...interesting...to fix. I'll try to take a look tomorrow!

**Comment by blaueeiner** [comment]
> > @kevmoo What is the current state of this issue? Can a proper fix be expected soon?
> 
> 
> 
> Hey @blaueeiner – it's going to be ...interesting...to fix. I'll try to take a look tomorrow!

@kevmoo For now I temporarily fixed this problem for me in a fork by simply checking if the map contains the key "nullValue" and then initializing the null value field with "NULL_VALUE" instead of getting the value from the map key which would return null instead of the string. I understand that this might not solve the problem in the master project because the code is generated via discovery files.

So if I understood right you are planning to somehow create overrides for the models? I would love to hear more about the details on how to approach and fix the problem and help solving this if help is needed 👌

**Comment by kevmoo** [comment]
FYI: this fix was released in v4
